### ISSUE TITLE
Compatibilité avec un Raspberry Pi 4 avec 4Go de Ram

### ISSUE THREAD

**Issue by Rathorian** [crazy-max/docker-pure-ftpd#1]
Bonjour,

Comme expliqué dans le titre, penses-tu que ton image est compatible avec le Raspberry Pi 4, étant donné que c'est un ARMv8 ? 

Car j'ai un problème pour le fonctionnement de cette image sur mon RPI4 que je ne peux pas expliquer en détail car je suis au travail.

J'utilise ton image sur un serveur AMD64, sans aucun problème et j'essaie également de la faire fonctionner sur mon RPI4 avec très exactement la même configuration, mais sans aucun succès.

**Comment by crazy-max** [comment]
Salut @Rathorian, tu pourrais créer une nouvelle issue et la mettre en anglais stp?
Profites-en également pour mettre les logs et toutes les infos dont j'ai besoin en créant un [bug report](https://github.com/crazy-max/docker-pure-ftpd/issues/new?template=bug_report.md).
Merci.
