### ISSUE TITLE
FTP client hanging at Retrieving directory listing...

### ISSUE THREAD

**Issue by mannemvamsi** [crazy-max/docker-pure-ftpd#15]
Hi,
I have connected using postgresql auth.
Connection is succesfull, but unable to retrieve directory listing

**ftp-client log**

```
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/home/ftpusers/ramana" is your current location
Command:	TYPE I
Response:	200 TYPE is now 8-bit binary
Command:	PASV
Response:	227 Entering Passive Mode (137,97,27,1,117,49)
Command:	MLSD
Error:	Connection timed out after 20 seconds of inactivity
```

**pg.conf**
```

PGSQLGetPW     SELECT password FROM users WHERE username='\L'

PGSQLGetDir    SELECT dir FROM users WHERE username='\L'
```

I have tried the following
1. Added "-j" to data/pureftpd.flags to auto create directory when logged in
2. Created directory "ramana" manually at /home/ftpusers

any pointers would be helpful

**Comment by crazy-max** [comment]
@mannemvamsi Please create a proper [bug report](https://github.com/crazy-max/docker-pure-ftpd/issues/new?template=bug_report.md).
