### ISSUE TITLE
Innumerable pure-uploadscript daemons are being created.

### ISSUE THREAD

**Issue by satishvmadala** [crazy-max/docker-pure-ftpd#18]
Hey!

I'm just wondering if any one of you have been using pure-uploadscript functionality and encountered the below problem:

![image](https://user-images.githubusercontent.com/950063/88270243-f30ba500-ccf2-11ea-901e-38786fe831ba.png)

At [https://github.com/crazy-max/docker-pure-ftpd/blob/master/rootfs/etc/cont-init.d/03-uploadscript.sh](rootfs/etc/cont-init.d/03-uploadscript.sh) pure-uploadscript demon is written to services.d and it is being called continuously. 

```
cat > /etc/services.d/pure-uploadscript/run <<EOL
#!/usr/bin/execlineb -P
with-contenv
pure-uploadscript --daemon --run ${UPLOADSCRIPT}
EOL
chmod +x /etc/services.d/pure-uploadscript/run
```
Is it supposed to have only one daemon running here? 

Thanks in advance.

**Comment by crazy-max** [comment]
Hi @satishvmadala, can you create a proper [bug report](https://github.com/crazy-max/docker-pure-ftpd/issues/new?template=bug_report.md) please? Thanks.

**Comment by crazy-max** [comment]
@satishvmadala Ok I've found the issue. I will push a fix asap.

**Comment by crazy-max** [comment]
@satishvmadala Should be fixed
