### ISSUE TITLE
Libsodium Support is Broken

### ISSUE THREAD

**Issue by dweingart** [crazy-max/docker-pure-ftpd#9]
I was having trouble getting argon2 hashing to work with the image and discovered that Libsodium support isn't compiled-in, due to a typo in the Dockerfile.

Changing [line 18](https://github.com/crazy-max/docker-pure-ftpd/blob/c423e5273eb9a11913069ff44675f5999f498253/Dockerfile#L18) from `libsodium` to `libsodium-dev` fixes the problem.

**Comment by crazy-max** [comment]
@dweingart Good catch, will fix that asap.

**Comment by crazy-max** [comment]
@dweingart Should be fixed
